# Generated by Django 5.2.13 on 2026-04-26 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_scan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuickUPCScan',
            new_name='Scan',
        ),
        migrations.RenameIndex(
            model_name='scan',
            new_name='inventory_s_user_id_0f0eed_idx',
            old_name='inventory_q_user_id_ac01cd_idx',
        ),
    ]
