# Generated by Django 5.2.13 on 2026-05-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_location_upcproduct_inventoryitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='custom_description',
            field=models.TextField(blank=True, default='', help_text='Override the product description'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='custom_name',
            field=models.CharField(blank=True, default='', help_text='Override the product name', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='inventory-items/%Y/%m/'),
        ),
    ]
